# todo use rabbitmq - deploy rabbit in kubernetes and expose monitoring ingress for auto
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: geoprice-data-service-production-mex-autoscale
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: geoprice-data-service-production-mex-deployment
  minReplicas: 8
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50