apiVersion: v1
kind: Service
metadata:
  name: redis-development-mex-service
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    application: redis
    application-type: database
    broker: redis
    environment: development
    owner: oscar
    type: deployment
    version: v0.1
  type: ClusterIP