apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
  labels:
    application: redis
    environment: development
    application-type: database
    owner: oscar
    version: v0.1
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: redis-dev-disk
    fsType: ext4