apiVersion: v1
kind: Service
metadata:
  name: geoprice-web-service-development-mex-deployment-service
spec:
  selector:
    application: geoprice-web-service
    environment: development
    application-type: web-service
    owner: oscar
    version: v0.1
    type: deployment
  ports:
    - name: geoprice-web-service-port
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
